### PR TITLE
Add base color selector

### PR DESCRIPTION
**Pull request by otacke**
Currently, Interactive Book uses a fixed blue color tone as base color that some other values are derived from.

When this pull request is merged in, the author will be able to select a custom base color in the editor. That base color will be used to
- change the respective color and its derived values in the view of Interactive Book
- override the blue base color that sub contents use with that base color to achieve a coherent visual experience

### CODE REVIEW

**Comment by fnoks** [comment]
I see you have created a lot of JavaScript logic for setting colors. I believe a much better approach would be to use CSS Custom properties (https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties). I.e: Use JS to generate CSS containing all variables and attach the style to the DOM. These variables can then be used in the regular CSS-files.

**Comment by otacke** [comment]
@fnoks Cool, I didn't know about CSS custom properties, but that's of course the way it should be done! Will change that.

**Comment by otacke** [comment]
@fnoks I changed the custom color styles to use CSS custom properties as suggested. Thanks a lot!

**Comment by mjwareha** [comment]
Hello good people - I see there are lots of amazing updates and improvements being made to the interactive book, is there any news on when these might be released as library updates for use in Wordpress?

Thanks,

Marcus

**Comment by otacke** [comment]
@mjwareha You can track the H5P core teams' progress for this pull request at https://h5ptechnology.atlassian.net/browse/HFP-3513. Once that's done _and_ the update is released, it will be available for all platforms automatically via the H5P Hub - there's no separate release for one platform such as WordPress.

I don't think that the H5P core team will announce exact dates, but given that the status of the issue is set to "Selected for development", it should be dealt with soon.

**Pull request merged**
