### PR TITLE
HFP-3225 Add support for getCurrentState function

### PR DESCRIPTION
**Pull request by otacke**
When merged in, Interactive Book will support the getCurrentState function and (given that the feature is activated) restore the previous state of Interactive Book itself (e.g. show previous progress) and of the subcontents if those support `getCurrentState` themselves.

### CODE REVIEW

**Comment by nenorojas** [comment]
Hi @otacke, we have tested the Interactive Book activity in Moodle 3.9 with this PR request, generating a new version of Interactive Book (1.4.1), the progress is saved properly, well done, BUT unfortunately it broke the submission of the activity. When you try to click on the submit button it does not send to the gradebook, this is the sample h5p, with sample activity we have used to install the modified library to Moodle (to whoever wants to try that, please use with care and do not update all existing activities of your Moodle to use that new version on live environment)
[berries_testv2.zip](https://github.com/h5p/h5p-interactive-book/files/7292412/berries_testv2.zip). 

Do you have an idea of when it will become merged to the official h5p libraries?

**Comment by nenorojas** [comment]
@otacke sorry if sounded that I was accusing your PR from breaking the submit, not at all. We were hoping to implement asap the feature you have implemented to a Moodle H5P Interactive Book activity, and our testing was going perfectly, as in, we could start answering the activities on the interactive book, moved to different page, logged off, logged in again and we could resume from where we stopped. But at the end, the submit button of the test activity stopped working. There must be something else missing in the process that was not the most straightforward until I could generate the h5p file above that installed a modified version of IB. Thank you for the attention to my question anyway.  CHeers

**Comment by otacke** [comment]
@nenorojas No offense taken :-) I suggest you first build Interactive Book from the latest version of the master branch and check whether that version works as expected. If it also shows that odd behavior, then it's something more general. If that in fact works, then something may have gone sideways in my feature addition. If you report bugs (ideally at https://h5p.org/forum/9), please don't forget to attach additional information (see top of https://h5p.org/forum/9) that will help to identify the origin of the problem. For H5P content types, the most useful information is usually the output of the development console if there's any.

**Comment by nenorojas** [comment]
@otacke thanks, I've raised with more details. https://h5p.org/node/1217290 It seems to work fine only with mod_hvp plugin for Moodle, when using the activity via Moodle core h5pactivity, it doesn't save the state.

**Comment by otacke** [comment]
@nenorojas That's to be expected. As far as I know, the moodle core integration doesn't support the save content state feature at all (yet).

**Comment by otacke** [comment]
@fnoks Pål, do you have any guess when this might find its way into the review pipeline? Just received another question regarding this feature.

**Comment by fnoks** [comment]
@otacke : Thank you for this PR. I did merge it in, but see a few things that should be addressed before this will be released:

1. Unnecessary data is stored (through getCurrentState). I.e: we should avoid storing data that can be recalculated. At least this goes for chapter.maxTasks and chapter.tasksLeft. These can be set on resume based on each section's taskDone.
2. If I leave the IB while viewing the summary page, it is not able to resume. I.e: the content part is empty in these cases.

Are these issues something you could address?

**Comment by otacke** [comment]
@fnoks Sure. I think I had a reason for storing these values, but that memory seems to have remained in May when I created the pull request.

**Comment by otacke** [comment]
@fnoks https://github.com/h5p/h5p-interactive-book/pull/79

**Pull request merged**
